// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoestoreSoulinthavong.Models;

namespace ShoestoreSoulinthavong.Migrations
{
    [DbContext(typeof(ShoeContext))]
    partial class ShoeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoestoreSoulinthavong.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RetailPrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Size")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            ShoeId = 1,
                            Brand = "Adidas",
                            Color = "Black",
                            Gender = "Men",
                            RetailPrice = 180.0,
                            Size = 9.5,
                            Style = "Sneaker"
                        },
                        new
                        {
                            ShoeId = 2,
                            Brand = "Nike",
                            Color = "Grey",
                            Gender = "Women",
                            RetailPrice = 90.0,
                            Size = 6.5,
                            Style = "Sneaker"
                        },
                        new
                        {
                            ShoeId = 3,
                            Brand = "Converse",
                            Color = "White",
                            Gender = "Unisex",
                            RetailPrice = 44.990000000000002,
                            Size = 8.0,
                            Style = "Sneaker"
                        },
                        new
                        {
                            ShoeId = 4,
                            Brand = "Birkenstocks",
                            Color = "Nude",
                            Gender = "Unisex",
                            RetailPrice = 99.950000000000003,
                            Size = 9.0,
                            Style = "Sandal"
                        },
                        new
                        {
                            ShoeId = 5,
                            Brand = "Teva",
                            Color = "Black",
                            Gender = "Unisex",
                            RetailPrice = 49.950000000000003,
                            Size = 5.0,
                            Style = "Sandal"
                        },
                        new
                        {
                            ShoeId = 6,
                            Brand = "Timberland",
                            Color = "Yellow",
                            Gender = "Men",
                            RetailPrice = 165.99000000000001,
                            Size = 8.0,
                            Style = "Boot"
                        },
                        new
                        {
                            ShoeId = 7,
                            Brand = "Uggs",
                            Color = "Chestnut",
                            Gender = "Women",
                            RetailPrice = 205.99000000000001,
                            Size = 5.0,
                            Style = "Boot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
